// <auto-generated />
namespace DAL
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedfriendships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedfriendships));
        
        string IMigrationMetadata.Id
        {
            get { return "201701192324164_Added friendships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
